---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: "pipeline"
spec:
  tasks:
    - name: task
      taskSpec:
        steps:
          - name: step-1
            image: registry.access.redhat.com/ubi9/ubi-micro
            script: |
              sleep 10s
              echo "I am doing nothing but looks like I'm doing something"
              exit 0
